### ISSUE TITLE
Remover Peças

### ISSUE THREAD

**Issue by Nico0504-lab** [B0yEditi0n/DamaPublicEditor#1]
a) Faltou um botão para retirar as peças do tabuleiro

**Comment by B0yEditi0n** [comment]
> a) Faltou um botão para retirar as peças do tabuleiro
> 
@Nico0504-lab 
Por hora eu deixe para selecionar e arrastar para fora do tabuleiro e peça será deletada, isso atende o problema? Caso não eu crio um botão de remoção

**Comment by Nico0504-lab** [comment]
ook

Em sex., 13 de set. de 2024 às 10:25, B0yEditi0n ***@***.***>
escreveu:

**Comment by B0yEditi0n** [comment]
Bom não sei se atendeu ou não como não obtive uma reposta eu vou fechar esse comentário
